version: 2.1
jobs:
  build-and-test:
    machine:
      image: ubuntu-2004:202104-01
        
    steps:
      - checkout
      - run: make deps
      - run: make lint
      - run: make test
workflows: Legia Warszawa To Najlepszy Klub
  basic:
    jobs:
      - build-and-test 